#!/bin/bash 
# builds a phat script with all plugins inside
usage='[[ ! -n "$1" ]] && { 
  grep "^# usage: " "$0" | while read line; do echo "${line}" | sed "s/^# //g"; done 
  echo -e "\nfor more info see:  http://coderofsalvation.github.io/framebuffer.bash";
  exit
}
"$@"
'
cat framebuffer.bash plugins/*.bash > fb
echo "$usage" >> fb 
chmod 755 fb
echo "done...now run: ./fb"
